"""initial schema

Revision ID: 2579b6f3f71c
Revises: 
Create Date: 2026-07-15 01:43:55.160724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2579b6f3f71c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('api_key_lookup_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('key_rotated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_lookup_hash'), 'users', ['api_key_lookup_hash'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic_prefix', sa.Text(), nullable=False),
    sa.Column('mqtt_username', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mqtt_username'),
    sa.UniqueConstraint('topic_prefix')
    )
    op.create_table('entities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('component_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('friendly_name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('device_class', sa.Text(), nullable=True),
    sa.Column('state_topic', sa.Text(), nullable=False),
    sa.Column('command_topic', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_api_key_lookup_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
